name: Chrome Extension CI

on:
  push:
    branches:
      - main  # Trigger on pushes to main; adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a recent Node.js version

      # Install dependencies for the extension
      - name: Install Dependencies
        run: |
          cd gitsense-extension
          npm install  # Install any Node.js dependencies if present (e.g., for build tools)

      # Build the extension (if applicable)
      - name: Build Extension
        run: |
          cd gitsense-extension
          # Add build steps if you have a build process (e.g., 'npm run build')
          # For now, assume the extension is ready in its current form

      # Package the extension into a .zip file
      - name: Package Extension
        run: |
          cd gitsense-extension
          zip -r gitsense-extension.zip . -x "*.git*"

      # Upload the artifact for manual use
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gitsense-extension
          path: gitsense-extension/gitsense-extension.zip
